### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Williampprado** [razorlikes/SpotifyTitleGrabber#2]
need a tutorial on how to use it, I couldn't use it because I'm not a programmer and I don't have an explanation here

**Comment by razorlikes** [comment]
What exactly do you need help with? Grab the latest release from [here](https://github.com/razorlikes/SpotifyTitleGrabber/releases/latest) and run it. 

The application is pretty self explanantory. Just play a song in Spotify and its title should show up in the text file at the path specified in the "Currently playing song file" box.
